import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [
    deviceorientation,
    setDeviceorientation,
  ] = useState<DeviceOrientationEvent>();
  useEffect(() => {
    const setValue = (e: DeviceOrientationEvent) => {
      console.log(e);
      setDeviceorientation(e);
    };
    window.addEventListener("deviceorientation", setValue);
    return () => {
      window.removeEventListener("deviceorientation", setValue);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>加速度センサーの値を取得する</div>
      <div>alpha: {deviceorientation?.alpha}</div>
      <div>beta: {deviceorientation?.beta}</div>
      <div>gamma: {deviceorientation?.gamma}</div>
    </>
  );
}
